INSERT INTO d_tipo_refeicao(id, nome) VALUES(1, 'Café da manhã');
INSERT INTO d_tipo_refeicao(id, nome) VALUES(2, 'Lanche da manhã');
INSERT INTO d_tipo_refeicao(id, nome) VALUES(3, 'Almoço');
INSERT INTO d_tipo_refeicao(id, nome) VALUES(4, 'Lanche da tarde');
INSERT INTO d_tipo_refeicao(id, nome) VALUES(5, 'Jantar');
INSERT INTO d_tipo_refeicao(id, nome) VALUES(6, 'Ceia');
SELECT * FROM d_tipo_refeicao;


INSERT INTO d_unidade_medida(id, nome) VALUES(1, 'miligrama');
INSERT INTO d_unidade_medida(id, nome) VALUES(2, 'grama');
INSERT INTO d_unidade_medida(id, nome) VALUES(3, 'mililitro');
INSERT INTO d_unidade_medida(id, nome) VALUES(4, 'litro');
INSERT INTO d_unidade_medida(id, nome) VALUES(5, 'unidade');
INSERT INTO d_unidade_medida(id, nome) VALUES(6, 'xícara');
INSERT INTO d_unidade_medida(id, nome) VALUES(7, 'colher (chá)');
INSERT INTO d_unidade_medida(id, nome) VALUES(8, 'colher (sopa)');
SELECT * FROM d_unidade_medida;


INSERT INTO d_ingrediente(id, nome) VALUES(1, 'Arroz');
INSERT INTO d_ingrediente(id, nome) VALUES(2, 'Feijão');
INSERT INTO d_ingrediente(id, nome) VALUES(3, 'Farinha de trigo');
INSERT INTO d_ingrediente(id, nome) VALUES(4, 'Açúcar');
INSERT INTO d_ingrediente(id, nome) VALUES(5, 'Sal');
INSERT INTO d_ingrediente(id, nome) VALUES(6, 'Óleo vegetal');
INSERT INTO d_ingrediente(id, nome) VALUES(7, 'Azeite de oliva');
INSERT INTO d_ingrediente(id, nome) VALUES(8, 'Leite');
INSERT INTO d_ingrediente(id, nome) VALUES(9, 'Manteiga');
INSERT INTO d_ingrediente(id, nome) VALUES(10, 'Margarina');
INSERT INTO d_ingrediente(id, nome) VALUES(11, 'Ovos');
INSERT INTO d_ingrediente(id, nome) VALUES(12, 'Frango');
INSERT INTO d_ingrediente(id, nome) VALUES(13, 'Carne bovina');
INSERT INTO d_ingrediente(id, nome) VALUES(14, 'Carne suína');
INSERT INTO d_ingrediente(id, nome) VALUES(15, 'Peixe');
INSERT INTO d_ingrediente(id, nome) VALUES(16, 'Alho');
INSERT INTO d_ingrediente(id, nome) VALUES(17, 'Cebola');
INSERT INTO d_ingrediente(id, nome) VALUES(18, 'Tomate');
INSERT INTO d_ingrediente(id, nome) VALUES(19, 'Cenoura');
INSERT INTO d_ingrediente(id, nome) VALUES(20, 'Batata');
INSERT INTO d_ingrediente(id, nome) VALUES(21, 'Batata-doce');
INSERT INTO d_ingrediente(id, nome) VALUES(22, 'Pimentão');
INSERT INTO d_ingrediente(id, nome) VALUES(23, 'Alface');
INSERT INTO d_ingrediente(id, nome) VALUES(24, 'Brócolis');
INSERT INTO d_ingrediente(id, nome) VALUES(25, 'Couve');
INSERT INTO d_ingrediente(id, nome) VALUES(26, 'Espinafre');
INSERT INTO d_ingrediente(id, nome) VALUES(27, 'Abobrinha');
INSERT INTO d_ingrediente(id, nome) VALUES(28, 'Berinjela');
INSERT INTO d_ingrediente(id, nome) VALUES(29, 'Milho');
INSERT INTO d_ingrediente(id, nome) VALUES(30, 'Ervilha');
INSERT INTO d_ingrediente(id, nome) VALUES(31, 'Grão-de-bico');
INSERT INTO d_ingrediente(id, nome) VALUES(32, 'Lentilha');
INSERT INTO d_ingrediente(id, nome) VALUES(33, 'Macarrão');
INSERT INTO d_ingrediente(id, nome) VALUES(34, 'Aveia');
INSERT INTO d_ingrediente(id, nome) VALUES(35, 'Amido de milho');
INSERT INTO d_ingrediente(id, nome) VALUES(36, 'Fermento químico');
INSERT INTO d_ingrediente(id, nome) VALUES(37, 'Fermento biológico');
INSERT INTO d_ingrediente(id, nome) VALUES(38, 'Leite condensado');
INSERT INTO d_ingrediente(id, nome) VALUES(39, 'Creme de leite');
INSERT INTO d_ingrediente(id, nome) VALUES(40, 'Iogurte');
INSERT INTO d_ingrediente(id, nome) VALUES(41, 'Queijo muçarela');
INSERT INTO d_ingrediente(id, nome) VALUES(42, 'Queijo parmesão');
INSERT INTO d_ingrediente(id, nome) VALUES(43, 'Queijo prato');
INSERT INTO d_ingrediente(id, nome) VALUES(44, 'Requeijão');
INSERT INTO d_ingrediente(id, nome) VALUES(45, 'Bacon');
INSERT INTO d_ingrediente(id, nome) VALUES(46, 'Presunto');
INSERT INTO d_ingrediente(id, nome) VALUES(47, 'Calabresa');
INSERT INTO d_ingrediente(id, nome) VALUES(48, 'Atum');
INSERT INTO d_ingrediente(id, nome) VALUES(49, 'Sardinha');
INSERT INTO d_ingrediente(id, nome) VALUES(50, 'Molho de tomate');
INSERT INTO d_ingrediente(id, nome) VALUES(51, 'Extrato de tomate');
INSERT INTO d_ingrediente(id, nome) VALUES(52, 'Shoyu');
INSERT INTO d_ingrediente(id, nome) VALUES(53, 'Vinagre');
INSERT INTO d_ingrediente(id, nome) VALUES(54, 'Mostarda');
INSERT INTO d_ingrediente(id, nome) VALUES(55, 'Ketchup');
INSERT INTO d_ingrediente(id, nome) VALUES(56, 'Maionese');
INSERT INTO d_ingrediente(id, nome) VALUES(57, 'Pimenta-do-reino');
INSERT INTO d_ingrediente(id, nome) VALUES(58, 'Páprica');
INSERT INTO d_ingrediente(id, nome) VALUES(59, 'Orégano');
INSERT INTO d_ingrediente(id, nome) VALUES(60, 'Louro');
INSERT INTO d_ingrediente(id, nome) VALUES(61, 'Cominho');
INSERT INTO d_ingrediente(id, nome) VALUES(62, 'Cheiro-verde');
INSERT INTO d_ingrediente(id, nome) VALUES(63, 'Coentro');
INSERT INTO d_ingrediente(id, nome) VALUES(64, 'Manjericão');
INSERT INTO d_ingrediente(id, nome) VALUES(65, 'Alecrim');
INSERT INTO d_ingrediente(id, nome) VALUES(66, 'Canela');
INSERT INTO d_ingrediente(id, nome) VALUES(67, 'Noz-moscada');
INSERT INTO d_ingrediente(id, nome) VALUES(68, 'Cravo');
INSERT INTO d_ingrediente(id, nome) VALUES(69, 'Chocolate');
INSERT INTO d_ingrediente(id, nome) VALUES(70, 'Cacau em pó');
INSERT INTO d_ingrediente(id, nome) VALUES(71, 'Baunilha');
INSERT INTO d_ingrediente(id, nome) VALUES(72, 'Mel');
INSERT INTO d_ingrediente(id, nome) VALUES(73, 'Açúcar mascavo');
INSERT INTO d_ingrediente(id, nome) VALUES(74, 'Açúcar de confeiteiro');
INSERT INTO d_ingrediente(id, nome) VALUES(75, 'Coco ralado');
INSERT INTO d_ingrediente(id, nome) VALUES(76, 'Leite de coco');
INSERT INTO d_ingrediente(id, nome) VALUES(77, 'Banana');
INSERT INTO d_ingrediente(id, nome) VALUES(78, 'Maçã');
INSERT INTO d_ingrediente(id, nome) VALUES(79, 'Limão');
INSERT INTO d_ingrediente(id, nome) VALUES(80, 'Laranja');
INSERT INTO d_ingrediente(id, nome) VALUES(81, 'Morango');
INSERT INTO d_ingrediente(id, nome) VALUES(82, 'Uva');
INSERT INTO d_ingrediente(id, nome) VALUES(83, 'Abacaxi');
INSERT INTO d_ingrediente(id, nome) VALUES(84, 'Mamão');
INSERT INTO d_ingrediente(id, nome) VALUES(85, 'Manga');
INSERT INTO d_ingrediente(id, nome) VALUES(86, 'Abacate');
INSERT INTO d_ingrediente(id, nome) VALUES(87, 'Castanha de caju');
INSERT INTO d_ingrediente(id, nome) VALUES(88, 'Nozes');
INSERT INTO d_ingrediente(id, nome) VALUES(89, 'Amendoim');
INSERT INTO d_ingrediente(id, nome) VALUES(90, 'Azeitona');
INSERT INTO d_ingrediente(id, nome) VALUES(91, 'Palmito');
INSERT INTO d_ingrediente(id, nome) VALUES(92, 'Cogumelo');
INSERT INTO d_ingrediente(id, nome) VALUES(93, 'Pepino');
INSERT INTO d_ingrediente(id, nome) VALUES(94, 'Rúcula');
INSERT INTO d_ingrediente(id, nome) VALUES(95, 'Agrião');
INSERT INTO d_ingrediente(id, nome) VALUES(96, 'Repolho');
INSERT INTO d_ingrediente(id, nome) VALUES(97, 'Beterraba');
INSERT INTO d_ingrediente(id, nome) VALUES(98, 'Mandioca');
INSERT INTO d_ingrediente(id, nome) VALUES(99, 'Farinha de mandioca');
INSERT INTO d_ingrediente(id, nome) VALUES(100, 'Polvilho');
SELECT * FROM d_ingrediente;